### ISSUE TITLE
CosmosCache cannot create or use containers when database account has Gremlin API enabled

### ISSUE THREAD

**Issue by AieatAssam** [Azure/Microsoft.Extensions.Caching.Cosmos#30]
When enabling Gremlin API, the database account can no longer be used for the distributed cache because it relies on /id primary key. 
Attempting to create a new container (even if in a new database) will result in the following exception:

`{"code":"BadRequest","message":"Partition key path /id is invalid for Gremlin API. The path cannot be '/id', '/label' or a nested path such as '/key/path'.\r\nActivityId: 0fe16a8c-7623-4c00-8c5d-420ede27c978, Microsoft.Azure.Documents.Common/2.11.0"},"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"https://localhost:8081","access-control-expose-headers":"Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Content-Type,x-ms-activity-id,x-ms-gatewayversion","content-type":"application/json","date":"Thu, 30 Jul 2020 14:49:27 GMT","server":"Microsoft-HTTPAPI/2.0","x-firefox-spdy":"h2","x-ms-activity-id":"0fe16a8c-7623-4c00-8c5d-420ede27c978","x-ms-gatewayversion":"version=2.11.0","x-ms-throttle-retry-count":0,"x-ms-throttle-retry-wait-time-ms":0},"activityId":"0fe16a8c-7623-4c00-8c5d-420ede27c978"}`

This is reproducible with CosmosDb emulator started with the following commandline arguments:
/EnableGremlinEndpoint /GremlinPort=8901

Since id property is not usable, it might be necessary to introduce a new property. I have tried creating a collection manually with partition key of /key but inserts then generate the following error:

```
Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: c053bcba-52af-41f6-bfff-71a8c742aab3; Reason: (Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}
ActivityId: c053bcba-52af-41f6-bfff-71a8c742aab3, Request URI: /apps/DocDbApp/services/DocDbServer5/partitions/a4cb4951-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.17763 cosmos-netstandard-sdk/3.11.2);
```

**Comment by ealsur** [comment]
This library uses the Cosmos DB SQL SDK, meant for SQL APIs, and it uses the container as a Key-Value pair container (you can check how the container is created [here](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L350) which reduces RU consumption by turning off indexing). There is no such limitation in SQL API.

The error you get when using a manually created container is because the point operations are passing the `id` as the partition key https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L91, which doesn't match your container definition.

If we change now which is the partition key we pass, or change which is the partition key definition used, it would break all current users of the library (and their caches).

So this would need to be a new options I guess. 

Did you fork the repo and found a possible solution?

**Comment by ealsur** [comment]
@AieatAssam Please see the linked PR, if you can, please clone that branch and verify that the proposed solution fixes your issue.

**Comment by ealsur** [comment]
Verified that the associated PR fix works with the Gremlin enabled Emulator.

**Comment by AieatAssam** [comment]
Lovely. Thank you for rapid response. Unfortunately we had to go with Redis implementation for the time being (this is for production workload so prerelease package was a no go). The other deciding factor was cost - I planned to reuse existing CosmosDb database account, but level of Redis we needed was still cheap enough.
However, I run quick test in LinqPad agains ComsosDb emulator and it behaves as expected. Great to see this addressed so quickly and in a reasonable, non-breaking fashion.
