### ISSUE TITLE
Integrate with the edge cache currently in preview

### ISSUE THREAD

**Issue by pb-adrianbezzina** [Azure/Microsoft.Extensions.Caching.Cosmos#47]
Do you have plans to add integration with the Azure Cosmos DB integrated cache:

https://docs.microsoft.com/en-us/azure/cosmos-db/integrated-cache

The integrated cache is automatically configured within the dedicated gateway. The integrated cache has two parts:

An item cache for point reads
A query cache for queries

**Comment by ealsur** [comment]
We already discussed this internally with @timsander1 - Currently integrated cache benefits mostly queries, and this library does not do any of them.

It could certainly be leveraged at some point, potentially when the integrated cache is out of preview and it achieves it's final form (availability is only on preview SDKs and a GA library cannot take dependency on that).

**Comment by ealsur** [comment]
Following the doc at https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-integrated-cache#adjust-maxintegratedcachestaleness, you can certainly pull the preview SDK that is >= the minimum required version for this library and use the connection string provided for the cache endpoint and set the Client configuration to Gateway.

The only thing that won't happen is that point reads won't have the `MaxIntegratedCacheStaleness` set, but otherwise, it would take advantage of the cache endpoint.
