### ISSUE TITLE
`DefaultTimeToLiveInMs` specified in milliseconds?

### ISSUE THREAD

**Issue by shibayan** [Azure/Microsoft.Extensions.Caching.Cosmos#51]
**Describe the bug**

I thought the value to be specified for `DefaultTimeToLiveInMs` was in milliseconds from the property name, but it seems that it actually needs to be specified in seconds.

It would be easier to understand if the units could be clarified in the document comments.

**Comment by ealsur** [comment]
https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/d0a1a602196f78057783274633943f50b74ff38d/src/CosmosCache.cs#L402-L403

This is a bug, the value is not being correctly changed when it's passed down. Sadly at this point we cannot change the property name because it would be considered a breaking change.

The service property is actually in seconds (https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live#time-to-live-for-containers-and-items), it was a miss that this property's name actually contains the suffix `InMs`.

I'll send a PR to fix it.

**Comment by ealsur** [comment]
@shibayan please confirm if you need a release to cover this gap.

**Comment by shibayan** [comment]
@ealsur Thanks for the quick response. This change looks good to me.
I hope the property name will be changed in the next major version update.

**Comment by ealsur** [comment]
@shibayan Created a tracking issue.

**Comment by ealsur** [comment]
New version with the fix released https://www.nuget.org/packages/Microsoft.Extensions.Caching.Cosmos/1.0.1
